module.exports = {
  blue: "#3070cd",
  green: "#76cca5",
  lightBlue: "#66c6ed",
  lightRed: "#ff8686",
  lightErrorColor: "#e75858",
  lightErrorVariantColor: "#ff8686",
  lightPlaceholderTextColor: "#a0aeb8",
  lightPrimaryAccentColor: "#1f5bb2",
  lightPrimaryBackgroundColor: "#ffffff",
  lightPrimaryBorderColor: "#598dd7",
  lightPrimaryColor: "#3070cd",
  lightPrimaryFocusBackgroundColor: "#e0f4fb",
  lightPrimaryHoverBackgroundColor: "#eff9fd",
  lightPrimaryLinkColor: "#3070cd",
  lightPrimaryTextColor: "#3c505d",
  lightSecondaryAccentColor: "#3fafdd",
  lightSecondaryBackgroundColor: "#f6f9fb",
  lightSecondaryBorderColor: "#cfd6db",
  lightSecondaryColor: "#66c6ed",
  lightSecondaryHoverBackgroundColor: "#e7ecf0",
  lightSecondaryTextColor: "#a0aeb8",
  red: "#e75858",
  white: "#ffffff",
  yellow: "#efc657",
};