name: "Chromatic"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths-ignore:
      - '.gitignore'
      - 'tsconfig.json'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        yarn
    - uses: chromaui/action@v1
      with:
        projectToken: q65anlqcdyq
